name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Run cmake
      run: cmake -S . -B build
    - name: Run make
      run: make build
