name: Build ecs for linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update submodules
      run: git submodule update --init --recursive --remote

    - name: Run cmake
      run: cmake -D CMAKE_CXX_COMPILER=g++-10.1 -S . -B build

    - name: Run make
      run: cd build && make

    - name: Run unittests
      run: cd build && unittests
